import DivisibilityNoncommutativeUfdsLemmaCanonicalLaneLean.NoncommutativeUfdPackage
import DivisibilityNoncommutativeUfdsLemmaCanonicalLaneLean.DivisibilityTheory
import DivisibilityNoncommutativeUfdsLemmaCanonicalLaneLean.AtomicCondition
import DivisibilityNoncommutativeUfdsLemmaCanonicalLaneLean.UniqueFactorisation
import DivisibilityNoncommutativeUfdsLemmaCanonicalLaneLean.DivisibilityNoncommutativeUfdsLemma

namespace HautevilleHouse
namespace DivisibilityNoncommutativeUfdsLemmaCanonicalLaneLean

-- Root module aggregating all submodules

end DivisibilityNoncommutativeUfdsLemmaCanonicalLaneLean
end HautevilleHouse
